### Context root path ########
server:
  servlet:
    context-path: /ecolis-ws
  port: 8081

spring:
  datasource:
    jdbc-url: jdbc:mysql://${YOUR_DATABASE_HOSTNAME}:${YOUR_SERVER_PORT}/${YOUR_DATABASE_NAME}?autoReconnect=true&useSSL=false
    username: ${YOUR_DATABASE_USER}
    password: ${YOUR_DATABASE_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    properties:
      hibernate:
        show_sql: false
      hibernate.ddl-auto: none
      hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  main:
    allow-bean-definition-overriding: true

# Micro services
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:7777/eureka/
#   instance:
#     instanceId: ${spring.application.name}:${random.int}