### Context root path ########
server:
  servlet:
    context-path: /ecolis-ws
  port: 8081

spring:
  datasource:
    jdbc-url: jdbc:h2:mem:${YOUR_DATABASE_NAME};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${YOUR_DATABASE_USER}
    password: ${YOUR_DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    properties:
      hibernate:
        show_sql: true
      hibernate.ddl-auto: update
      hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

# Micro services
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:7777/eureka/
#   instance:
#     instanceId: ${spring.application.name}:${random.int}
